### ISSUE TITLE
"Revian Frontiersmen" scenario causes an error.

### ISSUE THREAD

**Issue by someoneinapt** [Juanfrank/Revia4Nalesh-and-someoneinapt#4]
Only started happening after I installed the race patch.

![image](https://user-images.githubusercontent.com/64116830/79940743-7ac6e680-845a-11ea-80c9-cc8694b7252f.png)

**Comment by someoneinapt** [comment]
The scenario does actually work. The preview seems to be the only thing broken.

**Comment by Juanfrank** [comment]
Try using this branch https://github.com/Juanfrank/Revia4Nalesh-and-someoneinapt/tree/Reviaexclave

**Comment by someoneinapt** [comment]
Yep, works just fine,

**Comment by Juanfrank** [comment]
Fixed in main branch https://github.com/Juanfrank/Revia4Nalesh-and-someoneinapt/commit/7c0dbea434cb8698c128f03a4ad44dfa066759f9
